### ISSUE TITLE
For HID? Any barcode types? doesn't work

### ISSUE THREAD

**Issue by luxlux** [the-letter-e-production/jquery-pos#1]
Looks like this is what i'm searching for. :)

But unfortunately it's not described what your plugin exactly does. :(

I want to use it with a Motorola / Symbol DS6708 scanner, set into HID mode. (Q: Is the plugin made for HID mode scanners?)

I want to use it for different barcode types, like code 128, code 93, EAN, .... (Q: Is it limited to one type of code, or only to numbers?)

I have tried it with putting a "console.log('fired')" into your scan.pos.barcode event catcher block. But if i scan a barcode (type:EAN), there is no output. So it looks like, your event will not fired.

But on the console, the scaned barcodes will be shown (may be by your code or jquery.), if no other keyboard key was pressed in between. 

It would be nice, if you clould say me something about this.
thanks
Lutz

**Comment by luxlux** [comment]
Update: 
Now i found your article: http://www.devlifeline.com/2014/05/using-point-of-sale-hardware-in-cloud.html

possibly it would be useful to add it to the description / readme file, where the people search for it.

i have now programmed the the scanner to send an ENTER as sufix, now your event will be fired... :)

**Comment by ericuldall** [comment]
Yes. This plugin assumes an enter keypress to end capture.

You can also use this plugin for any type of barcode or credit card scanner that will send the enter code and uses keypress. To customize capture for different codes, you may pass a custom regexp into the options object. See options override: https://github.com/the-letter-e-production/jquery-pos#usage

**Comment by luxlux** [comment]
ok, looks simple to change it from only digits to accept more. thanks.
