### ISSUE TITLE
how to do dual data from scanner and prefix in the lib/scanner

### ISSUE THREAD

**Issue by patagoniahiker** [the-letter-e-production/jquery-pos#2]
Hi, I am still earning, apologies in advance if this seems very novice. First kudos on this work :+1:

I am also very glad that your lib exists :8ball: I have a scenario where 
-    Books             `B0291928891`    begin with  `B`  
-    Magazines      `M94379w5409`   begin with   `M`
  etc..

The regex '\d+' is throwing me off, because here it says _eventcode_-Access 
    `$(document).on('scan.pos.barcode', function(event){`
        //access `event.code` - `barcode data`  , **is this A-109293 coming from the scanner data or just the number?**
    `});`
1.   question So, in my scenario will the barcode scanner not read those B and M?
2.   do you have a prefix you recommend in using this?

thanks

**Comment by ericuldall** [comment]
If you want you can create your own custom regexp for barcode scanning. 

In the options object:

```
regexp: {
    scan: {
        barcode: 'CUSTOM REGEXP HERE' //regexp for barcode validation
    }
}
```

My default choice for regexp was used while testing very basic barcodes. You can easily use your own regexp if necessary.
